In [2]:
import numpy as np

In [247]:
#NUMPY ARRAY

a = np.array([1, 2, 3])     #1D Array -> vector
b = np.array([[1, 2, 3] , [3, 4, 5]])     #2D Array -> matrix of size 2*3
print(type(a))

In [313]:
c = np.array([[[1, 2],[4, 5]], [[6, 7], [8, 9]]])    #3D Array -> tensor
print(c)

[[[1 2]
  [4 5]]

 [[6 7]
  [8 9]]]


In [305]:
#ARRAY ATTRIBUTES

a = np.array([1,2,3])

print(a.itemsize)        #size of item (in byte)
print(a.dtype)           #type of item 
print(a.ndim)            #number of dimension
print(a.shape)           #shape of array
print(b.size)            #no. of items in array

4
int32
1
(3,)
6


In [306]:
b = np.array([[1, 2, 3] , [3, 4, 5]])

print(b.itemsize)        #size of item (in byte)
print(b.dtype)           #type of item 
print(b.ndim)            #number of dimension
print(b.shape)           #shape of array
print(b.size)            #no. of items in array

4
int32
2
(2, 3)
6


In [309]:
b = np.array([2.0, 3, 1.0])
print(b)
print(b.dtype)
print(b.itemsize)

[2. 3. 1.]
float64
8


In [310]:
b = np.array([1.0, 2.0, 3.0], dtype = np.float32)      #OR, b.astype(np.float32)
print(b.dtype)
print(b.itemsize)

float32
4


In [311]:
# MEMORY SPACE

import sys

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

print(sys.getsizeof(arr[0] * len(arr)))
print(sys.getsizeof(list[6]) * len(list))

28
280


In [312]:
# ARRAY INDEXING

a = np.array([1, 2, 3, 4])
print(a[0])

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(b[1,3])

c= np.array([[[1, 2],[4, 5]], [[6, 7], [8, 9]]])
print(c[1, 1, 0])

#print(c[0,1,0])

1
8
8


In [314]:
# ITERATING EVERY ELEMENTS

a = np.array([1, 2, 3, 4, 5, 6])
for i in a:
    print(i)

1
2
3
4
5
6


In [317]:
a = np.array([[[1, 2],[4, 5]], [[6, 7], [8, 9]]])
for i in a:
    for j in i:
        for k in j:
            print(k)

1
2
4
5
6
7
8
9


In [318]:
# Iterate using nditer

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
for x in np.nditer(a):             
    print(x)

1
2
3
4
5
6
7
8
9


In [322]:
# ARANGE
m1 = np.arange(2, 10, 2)     #similar to range function
print(m1)
#reshaping the matrix
m2 = np.arange(1, 11).reshape(5, 2)
print(m2)

#higher dimensional matrix
mn = np.arange(32).reshape(2,2,2,2,2)
print(mn)

[2 4 6 8]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[[[[ 0  1]
    [ 2  3]]

   [[ 4  5]
    [ 6  7]]]


  [[[ 8  9]
    [10 11]]

   [[12 13]
    [14 15]]]]



 [[[[16 17]
    [18 19]]

   [[20 21]
    [22 23]]]


  [[[24 25]
    [26 27]]

   [[28 29]
    [30 31]]]]]


In [323]:
#RANDOM

m3 = np.random.random((2,4))  #gives 2*4 matrix of random number between 0 and 1
print(m3)

[[0.68344883 0.878333   0.56432441 0.09691104]
 [0.97530953 0.74031925 0.12833868 0.19439487]]


In [325]:
print(np.random.randint(1, 100, size=(3,4)))

[[97 37 55 53]
 [39 67 96 74]
 [21 66 19 62]]


In [326]:
print(np.random.choice([0,1,2],size=10))

[0 0 1 1 2 1 2 2 0 2]


In [329]:
m4 = np.linspace(0, 10, 5, dtype = int)    #gives equal interval
print(m4)

['0.0' '2.5' '5.0' '7.5' '10.0']


In [338]:
#DATA DISTRIBUTION

m5 = np.random.choice([2, 4, 6, 8], p=[0.1, 0.3, 0.6, 0.0], size=(10, 10))      # p = probability
print(m5)

[[4 6 2 6 6 4 6 6 4 4]
 [4 4 6 6 6 6 6 6 6 4]
 [4 4 6 6 4 6 6 6 6 4]
 [6 6 6 6 6 6 6 6 4 6]
 [6 6 6 6 6 6 4 4 6 6]
 [6 4 6 6 4 4 4 6 6 6]
 [6 4 6 6 6 6 4 2 6 4]
 [6 6 6 6 6 6 4 4 4 6]
 [4 6 4 6 2 6 6 4 6 6]
 [2 6 6 6 4 2 4 6 6 4]]
65


In [342]:
#SHUFFLING THE ELEMENTS OF ARRAY

arr = np.array([1, 2, 3, 4, 5])
print(np.random.permutation(arr))

[5 1 3 2 4]


In [348]:
# ARRAY SLICING OF 1D

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[1:5])

[2 3 4 5]


In [349]:
print(a[1:-1])

[2 3 4 5 6 7 8]


In [350]:
print(a[1:7:2])
#print(a[::2])

[2 4 6]


In [351]:
# ARRAY SLICING OF 2D

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(b[1, 1:3])

[6 7]


In [352]:
print(b[0:2, 2])

[3 7]


In [353]:
print(b[0:2, 1:3])

[[2 3]
 [6 7]]


In [355]:
#ARRAY SLICING OF 3D

c= np.array([[[1, 2, 3, 4],[4, 5, 6, 7]], [[6, 7, 8, 9], [8, 9, 10, 11]]])
print(c)
print(c[0:1, 1:2, :3])

[[[ 1  2  3  4]
  [ 4  5  6  7]]

 [[ 6  7  8  9]
  [ 8  9 10 11]]]
[[[4 5 6]]]


In [356]:
#MATRIX

print(np.zeros((2,2)))#all 0s

[[0. 0.]
 [0. 0.]]


In [357]:
print(np.ones((2,2)))         #all 1s

[[1. 1.]
 [1. 1.]]


In [358]:
print(np.eye(3))              #unitary mat or np.identity(3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [359]:
print(np.full((2,2),17))      #full of 17

[[17 17]
 [17 17]]


In [361]:
print(np.full_like(c, 9)) 
print(c)

[[[9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]]]
[[[ 1  2  3  4]
  [ 4  5  6  7]]

 [[ 6  7  8  9]
  [ 8  9 10 11]]]


In [362]:
#STACKING MATRIX UP

mat1 = np.array([[1,2],[2 , 3]])
mat2 = np.array([[2,1],[3 , 3]])
print(np.hstack((mat1, mat2)))
print(np.vstack((mat1, mat2)))

[[1 2 2 1]
 [2 3 3 3]]
[[1 2]
 [2 3]
 [2 1]
 [3 3]]


In [367]:
#SPLITING OF MATRIX

m = np.arange(16).reshape(4,4)
print(np.hsplit(m, 2))
print(np.vsplit(m, 2))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [369]:
#ARRAY SEARCH

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 != 0)         #gives index of the condn
print(x)    

(array([0, 2, 4, 6], dtype=int64),)


In [ ]:
z = np.array([[1,2],[3,4],[5,6]])
print(z)

bool_indx = z > 3 
print(bool_indx)      #give boolen values in the index of elements

In [ ]:
print(z[bool_indx])   #gives items of 'True' boolean

In [ ]:
print(np.where(z>3, z, -1))    #in place of 'False', gives given element

In [ ]:
#SORING THE MATRIX ELEMENTS

a = np.array([5, 7, 1, 4, 9, 0, 1])
print(np.sort(a))

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

In [242]:
#MATRIX_OPERATIONS

m = np.array([[2, 2],[4, 3]])
print(np.transpose(m))  #or print(m2.T)

In [ ]:
print(np.linalg.det(m))    #determinant of a matricx

In [222]:
print(np.linalg.inv(m)) #inverse

In [223]:
print(np.diag(m))    #diagonal

In [ ]:
print(m.flatten())     #give 1D array OR m.ravel()

#v = np.arange(1, 9).reshape(2, 2, 2)
#print(v)
#print(v.flatten())

In [241]:
m1 = np.array([[2, 2],[2, 3]])
m2 = np.array([[1, 2],[3, 2]])

In [ ]:
#Arithmetic Operation

#addition/substraction
print(2 + m1)
print(m1 + m2)

In [ ]:
#Multiplication/divison

print(2 * m1)
print(m1 * m2)

In [ ]:
#Dot Product

print(np.dot(m1,m2))     # OR print(m1 @ m2)

In [240]:
#ARRAY FUNCTION

m = np.random.randint(1, 100, (3,3))
print(m)

In [ ]:
print(np.max(m))
print(np.min(m))
print(np.sum(m))
print(np.prod(m))      #product

In [ ]:
print(np.max(m, axis=0))   #axis=0 -> column 
print(np.min(m, axis=1))   #axis=1 -> row

In [239]:
#STAT(MEAN/MEDIAN/STD/VAR)

print(np.mean(m))
print(np.median(m))
print(np.std(m))
print(np.var(m))

In [238]:
#EIGEN VALUE

m = np.array([[1,2],[2,1]])
eig_val, eig_vec = np.linalg.eig(m)
print(eig_val)
print(eig_vec)

In [237]:
#SOLVING LINEAR EQUATION

#3x + y = 21
#2x + 3y = 28

coff = np.array([[3, 1], [2, 3]])
cont = np.array([21, 28])
soln = np.linalg.solve(coff, cont)
print(soln)